# This is a generated file. Not intended for manual editing.
services:
  backend:
    build:
      context: "C:\\Users\\emzi0\\Documents\\Visual Studio 2022\\Projects\\Emzi0767.NetworkSelfService"
      dockerfile: "src/Emzi0767.NetworkSelfService.Backend/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "nss2-backend:dev"
    ports:
    - "127.0.0.1:57017:57000"
    - "127.0.0.1:57217:57200"
    - "127.0.0.1:57417:57400"
    volumes:
    - "C:\\Users\\emzi0\\Documents\\Visual Studio 2022\\Projects\\Emzi0767.NetworkSelfService\\\
      src\\Emzi0767.NetworkSelfService.Backend:/app:rw"
    - "C:\\Users\\emzi0\\Documents\\Visual Studio 2022\\Projects\\Emzi0767.NetworkSelfService:/src:rw"
    - "C:\\Users\\emzi0\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\emzi0\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.4\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.3.2\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\emzi0\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_1_23_23_43_35:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
